apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: test-7-24
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-7-24 
  name: test-7-24
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: test-7-24 
